{
    'name': 'Scale Integration Base',
    'version': '19.0.1.0.0',
    'category': 'Inventory/Stock',
    'summary': 'Base module for weighbridge scale integration',
    'author': 'Gemy',
    'website': 'https://www.example.com',
    'license': 'LGPL-3',
    'depends': ['mail', 'web', 'product'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/truck_weighing_reports.xml',
        'views/truck_weighing_views.xml',
        'views/weighing_scale_views.xml',
        'views/truck_fleet_views.xml',
        'views/res_users_views.xml',
        'views/product_views.xml',
        'views/menu_items_views.xml',
    ],
    'installable': True,
    'application': True,
}
